[package]
name = "day01"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
nom.workspace = true
alga = "0.9"

[dev-dependencies]
criterion.workspace = true

[[bench]]
name = "bench"
harness = false
